/**
 * Hand-maintained catalog ids for ITEMS (tiles, resources, tools, aliases).
 * When adding an item: add enum member(s) here, then add the row in constants.ts ITEMS.
 */

export enum TileKey {
  TileGrassGrass = "tile_grass_grass",
  TileGrassMeadow = "tile_grass_meadow",
  TileGrassSpiky = "tile_grass_spiky",
  TileGrainWheat = "tile_grain_wheat",
  TileBirdTurkey = "tile_bird_turkey",
  TileBirdClover = "tile_bird_clover",
  TileBirdMelon = "tile_bird_melon",
  TileVegCarrot = "tile_veg_carrot",
  TileVegEggplant = "tile_veg_eggplant",
  TileVegTurnip = "tile_veg_turnip",
  TileVegBeet = "tile_veg_beet",
  TileVegCucumber = "tile_veg_cucumber",
  TileVegSquash = "tile_veg_squash",
  TileVegMushroom = "tile_veg_mushroom",
  TileVegPepper = "tile_veg_pepper",
  TileVegBroccoli = "tile_veg_broccoli",
  TileGrassHeather = "tile_grass_heather",
  TileGrainCorn = "tile_grain_corn",
  TileGrainBuckwheat = "tile_grain_buckwheat",
  TileGrainManna = "tile_grain_manna",
  TileGrainRice = "tile_grain_rice",
  TileFruitApple = "tile_fruit_apple",
  TileFruitPear = "tile_fruit_pear",
  TileFruitGoldenApple = "tile_fruit_golden_apple",
  TileFruitBlackberry = "tile_fruit_blackberry",
  TileFruitRambutan = "tile_fruit_rambutan",
  TileFruitStarfruit = "tile_fruit_starfruit",
  TileFruitCoconut = "tile_fruit_coconut",
  TileFruitLemon = "tile_fruit_lemon",
  TileFruitJackfruit = "tile_fruit_jackfruit",
  TileFlowerPansy = "tile_flower_pansy",
  TileFlowerWaterLily = "tile_flower_water_lily",
  TileTreeOak = "tile_tree_oak",
  TileTreeBirch = "tile_tree_birch",
  TileTreeWillow = "tile_tree_willow",
  TileTreeFir = "tile_tree_fir",
  TileTreeCypress = "tile_tree_cypress",
  TileTreePalm = "tile_tree_palm",
  TileBirdPheasant = "tile_bird_pheasant",
  TileBirdChicken = "tile_bird_chicken",
  TileBirdHen = "tile_bird_hen",
  TileBirdRooster = "tile_bird_rooster",
  TileBirdWildGoose = "tile_bird_wild_goose",
  TileBirdGoose = "tile_bird_goose",
  TileBirdParrot = "tile_bird_parrot",
  TileBirdPhoenix = "tile_bird_phoenix",
  TileBirdDodo = "tile_bird_dodo",
  TileBirdPigInDisguise = "tile_bird_pig_in_disguise",
  TileHerdPig = "tile_herd_pig",
  TileHerdHog = "tile_herd_hog",
  TileHerdBoar = "tile_herd_boar",
  TileHerdWarthog = "tile_herd_warthog",
  TileHerdSheep = "tile_herd_sheep",
  TileHerdAlpaca = "tile_herd_alpaca",
  TileHerdGoat = "tile_herd_goat",
  TileHerdRam = "tile_herd_ram",
  TileCattleCow = "tile_cattle_cow",
  TileCattleLonghorn = "tile_cattle_longhorn",
  TileCattleTriceratops = "tile_cattle_triceratops",
  TileMountHorse = "tile_mount_horse",
  TileMountDonkey = "tile_mount_donkey",
  TileMountMoose = "tile_mount_moose",
  TileMountMammoth = "tile_mount_mammoth",
  TileMineStone = "tile_mine_stone",
  TileMineIronOre = "tile_mine_iron_ore",
  TileMineCopperOre = "tile_mine_copper_ore",
  TileMineCoal = "tile_mine_coal",
  TileMineGem = "tile_mine_gem",
  TileMineGold = "tile_mine_gold",
  TileMineSilver = "tile_mine_silver",
  TileCoinGolden = "tile_coin_golden",
  TileSpecialDirt = "tile_special_dirt",
  TileFishSardine = "tile_fish_sardine",
  TileFishMackerel = "tile_fish_mackerel",
  TileFishClam = "tile_fish_clam",
  TileFishOyster = "tile_fish_oyster",
  TileFishKelp = "tile_fish_kelp",
  TileFishCocoa = "tile_fish_cocoa",
  TileFishInk = "tile_fish_ink",
  TileFishJade = "tile_fish_jade",
  TileSpecialGiantPearl = "tile_special_giant_pearl",
}

export enum ResourceKey {
  Flour = "flour",
  Plank = "plank",
  Dirt = "dirt",
  Jam = "jam",
  Soup = "soup",
  Pie = "pie",
  Honey = "honey",
  Meat = "meat",
  Milk = "milk",
  Horseshoe = "horseshoe",
  Eggs = "eggs",
  HayBundle = "hay_bundle",
  Bread = "bread",
  Supplies = "supplies",
  Block = "block",
  CutGem = "cut_gem",
  Coke = "coke",
  IronBar = "iron_bar",
  CopperBar = "copper_bar",
  GoldBar = "gold_bar",
  SilverBar = "silver_bar",
  FishFillet = "fish_fillet",
  FishOil = "fish_oil",
  SeaShells = "sea_shells",
  Pearls = "pearls",
  Cocoa = "cocoa",
  Ink = "ink",
  Jade = "jade",
  Honeyroll = "honeyroll",
  Harvestpie = "harvestpie",
  Preserve = "preserve",
  Tincture = "tincture",
  IronHinge = "iron_hinge",
  Cobblepath = "cobblepath",
  Lantern = "lantern",
  Goldring = "goldring",
  Gemcrown = "gemcrown",
  Ironframe = "ironframe",
  Stonework = "stonework",
  Chowder = "chowder",
  FishOilBottled = "fish_oil_bottled",
  CuredMeat = "cured_meat",
  IronRation = "iron_ration",
  FestivalLoaf = "festival_loaf",
  WeddingPie = "wedding_pie",
}

export enum ToolKey {
  Clear = "clear",
  Basic = "basic",
  Rare = "rare",
  Shuffle = "shuffle",
  Bomb = "bomb",
  Rake = "rake",
  Axe = "axe",
  Sickle = "sickle",
  Fertilizer = "fertilizer",
  Cat = "cat",
  BirdCage = "bird_cage",
  ScytheFull = "scythe_full",
  Rifle = "rifle",
  Hound = "hound",
  Hoe = "hoe",
  StoneHammer = "stone_hammer",
  IronPick = "iron_pick",
  BirdFeed = "bird_feed",
  Sapling = "sapling",
  WaterPump = "water_pump",
  Explosives = "explosives",
  Trimmer = "trimmer",
  Plough = "plough",
  FruitPicker = "fruit_picker",
  HerdersCrook = "herders_crook",
  MilkChurn = "milk_churn",
  Saddle = "saddle",
  Bee = "bee",
  Terrier = "terrier",
  Drill = "drill",
  CoalHammer = "coal_hammer",
  GoldPick = "gold_pick",
  Magnet = "magnet",
  CoalTransmuter = "coal_transmuter",
  MagicWand = "magic_wand",
  Hourglass = "hourglass",
  MagicSeed = "magic_seed",
  MagicFertilizer = "magic_fertilizer",
  GoldenApple = "golden_apple",
  GoldenCarrot = "golden_carrot",
  GoldenIdol = "golden_idol",
  GoldenSheep = "golden_sheep",
  PhilosophersStone = "philosophers_stone",
  MinersHat = "miners_hat",
  Auger = "auger",
  BlastCharge = "blast_charge",
}

export enum ItemAliasKey {
  IronFrame = "iron_frame",
  GemCrown = "gem_crown",
  GoldRing = "gold_ring",
}

/** Every key that may index `ITEMS`. */
export type ItemKey = TileKey | ResourceKey | ToolKey | ItemAliasKey;

/** Runtime iteration (boundary checks, Dev Panel lists). */
export const ALL_ITEM_KEY_VALUES: readonly ItemKey[] = [
  ...Object.values(TileKey),
  ...Object.values(ResourceKey),
  ...Object.values(ToolKey),
  ...Object.values(ItemAliasKey),
] as ItemKey[];


export const TILE_KEY_VALUES = Object.values(TileKey);
export const RESOURCE_KEY_VALUES = Object.values(ResourceKey);
export const TOOL_KEY_VALUES = Object.values(ToolKey);
export const ITEM_ALIAS_VALUES = Object.values(ItemAliasKey);
