/**
 * Hand-maintained catalog enum — edit when adding ids, then update the matching config map.
 */

/** Recipe catalog keys (includes rec_* and item-key aliases). */
export enum RecipeKey {
  RecAxe = "rec_axe",
  RecBee = "rec_bee",
  RecBirdCage = "rec_bird_cage",
  RecBirdFeed = "rec_bird_feed",
  RecBread = "rec_bread",
  RecCat = "rec_cat",
  RecChowder = "rec_chowder",
  RecCoalHammer = "rec_coal_hammer",
  RecCoalTransmuter = "rec_coal_transmuter",
  RecCobblepath = "rec_cobblepath",
  RecCuredMeat = "rec_cured_meat",
  RecDrill = "rec_drill",
  RecExplosives = "rec_explosives",
  RecFertilizer = "rec_fertilizer",
  RecFestivalLoaf = "rec_festival_loaf",
  RecFishOilBot = "rec_fish_oil_bot",
  RecFruitPicker = "rec_fruit_picker",
  RecGemcrown = "rec_gemcrown",
  RecGoldPick = "rec_gold_pick",
  RecGoldring = "rec_goldring",
  RecHarvestpie = "rec_harvestpie",
  RecHerdersCrook = "rec_herders_crook",
  RecHoe = "rec_hoe",
  RecHoneyroll = "rec_honeyroll",
  RecHound = "rec_hound",
  RecIronHinge = "rec_iron_hinge",
  RecIronPick = "rec_iron_pick",
  RecIronRation = "rec_iron_ration",
  RecIronframe = "rec_ironframe",
  RecLantern = "rec_lantern",
  RecMagnet = "rec_magnet",
  RecMilkChurn = "rec_milk_churn",
  RecPlough = "rec_plough",
  RecPreserve = "rec_preserve",
  RecRake = "rec_rake",
  RecRifle = "rec_rifle",
  RecSaddle = "rec_saddle",
  RecSapling = "rec_sapling",
  RecScytheFull = "rec_scythe_full",
  RecSickle = "rec_sickle",
  RecStoneHammer = "rec_stone_hammer",
  RecStonework = "rec_stonework",
  RecSupplies = "rec_supplies",
  RecTerrier = "rec_terrier",
  RecTincture = "rec_tincture",
  RecTrimmer = "rec_trimmer",
  RecWaterPump = "rec_water_pump",
  RecWeddingPie = "rec_wedding_pie",
}

export const RECIPE_KEY_VALUES = Object.values(RecipeKey);
