/** @type {import('tailwindcss').Config} */
export default {
  content: ["./index.html", "./main.jsx", "./prototype.jsx", "./src/**/*.{js,jsx}"],
  theme: {
    extend: {
      colors: {
        parchment:        "var(--parchment)",
        "parchment-dim":  "var(--parchment-dim)",
        "parchment-soft": "var(--parchment-soft)",
        paper:            "var(--paper)",
        "paper-soft":     "var(--paper-soft)",
        iron:             "var(--iron)",
        "iron-soft":      "var(--iron-soft)",
        "iron-deep":      "var(--iron-deep)",
        ink:              "var(--ink)",
        "ink-soft":       "var(--ink-soft)",
        "ink-mid":        "var(--ink-mid)",
        "ink-light":      "var(--ink-light)",
        "panel-edge":     "var(--panel-edge)",
        cream:            "var(--cream)",
        "cream-soft":     "var(--cream-soft)",
        ember:            "var(--ember)",
        "ember-soft":     "var(--ember-soft)",
        "ember-hot":      "var(--ember-hot)",
        gold:             "var(--gold)",
        "gold-soft":      "var(--gold-soft)",
        "gold-bright":    "var(--gold-bright)",
        "gold-warm":      "var(--gold-warm)",
        moss:             "var(--moss)",
        "moss-soft":      "var(--moss-soft)",
        indigo:           "var(--indigo)",
        rose:             "var(--rose)",
        slate:            "var(--slate)",
        "bg-darkest":     "var(--bg-darkest)",
        "bg-darker":      "var(--bg-darker)",
        "bg-dark":        "var(--bg-dark)",
        "bg-frame":       "var(--bg-frame)",
        "bg-warm":        "var(--bg-warm)",

        /* Semantic UI chrome — pairs with the .hl-* component classes. */
        "panel-border":   "var(--panel-border)",
        "card-bg":        "var(--card-bg)",
        "card-border":    "var(--card-border)",
        "well-bg":        "var(--well-bg)",
        "well-border":    "var(--well-border)",
        "on-panel":       "var(--on-panel)",
        "on-panel-dim":   "var(--on-panel-dim)",
        "on-panel-faint": "var(--on-panel-faint)",
        "on-panel-label": "var(--on-panel-label)",
        "on-dark":        "var(--on-dark)",
        "on-dark-dim":    "var(--on-dark-dim)",
        "on-dark-faint":  "var(--on-dark-faint)",
        "on-dark-label":  "var(--on-dark-label)",
      },
      fontSize: {
        micro:    ["var(--text-micro)",   { lineHeight: "var(--leading-tight)" }],
        caption:  ["var(--text-caption)", { lineHeight: "var(--leading-snug)" }],
        body:     ["var(--text-body)",    { lineHeight: "var(--leading-normal)" }],
        "body-lg":["var(--text-body-lg)", { lineHeight: "var(--leading-normal)" }],
        large:    ["var(--text-large)",   { lineHeight: "var(--leading-normal)" }],
        h3:       ["var(--text-h3)",      { lineHeight: "var(--leading-snug)" }],
        h2:       ["var(--text-h2)",      { lineHeight: "var(--leading-snug)" }],
        h1:       ["var(--text-h1)",      { lineHeight: "var(--leading-tight)" }],
      },
      spacing: {
        tap:             "var(--tap-min)",
        "chrome-top":    "var(--chrome-top)",
        "chrome-bottom": "var(--chrome-bottom)",
        "safe-top":      "var(--safe-top)",
        "safe-bottom":   "var(--safe-bottom)",
      },
      borderRadius: {
        pill: "var(--radius-pill)",
      },
      screens: {
        md: "768px",
      },
    },
  },
  plugins: [],
};
