export const BEASTS = {
  meadowfox: {
    id: "meadowfox",
    name: "Meadow Fox",
    species: "Fox",
    icon: "🦊",
    biome: "farm",
    food: "berry",
    yields: "hay",
    baseYield: 3,
    tameCost: { resource: "berry", amount: 5 },
    flavor: "A russet streak at dawn — the Meadow Fox grazes the hedgerows for bright berries.",
  },
  craghen: {
    id: "craghen",
    name: "Crag Hen",
    species: "Hen",
    icon: "🐔",
    biome: "farm",
    food: "hay",
    yields: "egg",
    baseYield: 2,
    tameCost: { resource: "hay", amount: 6 },
    flavor: "Stout and warm-feathered, the Crag Hen clucks contentedly amid the haystack.",
  },
  mosselk: {
    id: "mosselk",
    name: "Moss Elk",
    species: "Elk",
    icon: "🦌",
    biome: "farm",
    food: "hay",
    yields: "plank",
    baseYield: 2,
    tameCost: { resource: "hay", amount: 8 },
    flavor: "Great antlers draped in lichen — the Moss Elk strips bark for you at first light.",
  },
  cinderbat: {
    id: "cinderbat",
    name: "Cinder Bat",
    species: "Bat",
    icon: "🦇",
    biome: "mine",
    food: "coal",
    yields: "ore",
    baseYield: 2,
    tameCost: { resource: "coal", amount: 5 },
    flavor: "Born in the furnace seam, the Cinder Bat flickers through the shafts sniffing out ore.",
  },
  lodecrab: {
    id: "lodecrab",
    name: "Lode Crab",
    species: "Crab",
    icon: "🦀",
    biome: "mine",
    food: "stone",
    yields: "ingot",
    baseYield: 1,
    tameCost: { resource: "stone", amount: 6 },
    flavor: "Its shell is raw iron; the Lode Crab refines ore with uncanny patience.",
  },
  lanternowl: {
    id: "lanternowl",
    name: "Lantern Owl",
    species: "Owl",
    icon: "🦉",
    biome: "mine",
    food: "berry",
    yields: "gem",
    baseYield: 1,
    tameCost: { resource: "berry", amount: 10 },
    flavor: "Rare beyond reckoning — eyes like cut gems, it roosts only where crystals grow.",
  },
};

export const BEAST_KEYS = Object.keys(BEASTS);
export const FARM_BEASTS = BEAST_KEYS.filter((k) => BEASTS[k].biome === "farm");
export const MINE_BEASTS = BEAST_KEYS.filter((k) => BEASTS[k].biome === "mine");
