/**
 * ToolAcquisition.tsx — "How to get it" section for tool (item) articles.
 *
 * Lists every way a tool enters the player's (global) tool bag, derived from the
 * catalog so it can't drift:
 *   - crafted at a station (recipes whose output is this tool)
 *   - generated by a building over time (grant_tool abilities)
 *   - Town-Hall provisions (the CIVIC_PROVISIONS building→tool map, ~every 8h)
 *   - the daily login ladder (DAILY_REWARDS)
 * Falls back to a note when a tool is only obtainable through special/premium
 * means (e.g. portal summons), so a tool page always answers "how do I get this?".
 *
 * React Compiler is on — no manual useMemo/useCallback.
 */

import React from "react";
import { COLORS } from "../../shared.jsx";
import { buildRecipesByOutput } from "../../recipeCatalog.js";
import { BUILDINGS, DAILY_REWARDS } from "../../../constants.js";
import { CIVIC_PROVISIONS } from "../../../features/civicEconomy/data.js";
import { ConceptRefForKey, resolveConceptId } from "../refs.js";
import { iconLabel } from "../../../textures/iconRegistry.js";
import { AmountChips } from "../EntityVisual.jsx";

interface BuildingAbilityLike {
  id?: string;
  params?: Record<string, unknown>;
  trigger?: string;
}
interface BuildingLike {
  id: string;
  name?: string;
  abilities?: BuildingAbilityLike[];
}
interface DailyEntryLike {
  coins?: number;
  tool?: string;
  amount?: number;
}

function cadence(trigger?: string): string {
  switch (trigger) {
    case "season_end":
      return "at the end of each season";
    case "session_end":
      return "after each session";
    default:
      return trigger ? trigger.replace(/_/g, " ") : "periodically";
  }
}

/** Inline entity link when the key resolves to a wiki concept, else a plain label. */
function Ref({ k }: { k: string }) {
  if (resolveConceptId(k) != null) return <ConceptRefForKey entityKey={k} variant="inline" />;
  return <span style={{ fontWeight: 600 }}>{iconLabel(k) ?? k}</span>;
}

export interface AcquisitionRow {
  key: string;
  label: React.ReactNode;
  detail?: React.ReactNode;
}

/** Every catalog-derived way to acquire the tool, in display order. */
export function toolAcquisitionRows(toolId: string): AcquisitionRow[] {
  const rows: AcquisitionRow[] = [];

  // 1) Crafted at a station.
  const recipes = buildRecipesByOutput()[toolId] ?? [];
  for (const rec of recipes) {
    rows.push({
      key: `craft:${rec.recId}`,
      label: (
        <>
          Crafted at <Ref k={rec.station} />
        </>
      ),
      detail:
        Object.keys(rec.inputs).length > 0 ? <AmountChips amounts={rec.inputs} /> : undefined,
    });
  }

  // 2) Generated by a building over time (grant_tool ability).
  for (const raw of BUILDINGS) {
    const b = raw as BuildingLike;
    for (const ab of b.abilities ?? []) {
      if (ab.id === "grant_tool" && ab.params?.tool === toolId) {
        const amount = typeof ab.params?.amount === "number" ? ab.params.amount : 1;
        rows.push({
          key: `grant:${b.id}`,
          label: (
            <>
              Produced by <Ref k={b.id} />
            </>
          ),
          detail: (
            <span>
              {amount} {cadence(ab.trigger)}
            </span>
          ),
        });
      }
    }
  }

  // 3) Town-Hall provisions (free tool crate, ~every 8h).
  for (const [buildingId, entry] of Object.entries(CIVIC_PROVISIONS)) {
    if (entry.tool === toolId) {
      rows.push({
        key: `civic:${buildingId}`,
        label: (
          <>
            Town Hall provisions from <Ref k={buildingId} />
          </>
        ),
        detail: <span>{entry.amount} per collection (~every 8h)</span>,
      });
    }
  }

  // 4) Daily login ladder.
  const days: string[] = [];
  for (const [day, reward] of Object.entries(DAILY_REWARDS as Record<string, DailyEntryLike>)) {
    if (reward?.tool === toolId) days.push(day);
  }
  if (days.length > 0) {
    rows.push({
      key: "daily",
      label: <>Daily login reward</>,
      detail: <span>day {days.join(", ")}</span>,
    });
  }

  return rows;
}

/** TOC gate — a tool article always answers "how is it acquired". */
export function hasToolAcquisition(_toolId: string): boolean {
  return true;
}

export interface ToolAcquisitionProps {
  toolId: string;
}

export function ToolAcquisition({ toolId }: ToolAcquisitionProps) {
  const rows = toolAcquisitionRows(toolId);

  return (
    <section id="tool-acquisition">
      <h2 className="wiki-section-heading mb-2">How to get it</h2>
      <div
        style={{
          padding: "12px 14px",
          borderRadius: 10,
          background: COLORS.parchmentDeep,
          border: `1px solid ${COLORS.border}`,
          display: "flex",
          flexDirection: "column",
          gap: 10,
        }}
      >
        {rows.length === 0 ? (
          <p
            className="text-[13px] leading-relaxed"
            style={{ color: COLORS.inkSubtle, margin: 0, fontStyle: "italic" }}
          >
            Not craftable — earned through special events or portal summons.
          </p>
        ) : (
          rows.map((r) => (
            <div
              key={r.key}
              style={{ display: "flex", flexWrap: "wrap", gap: 8, alignItems: "center" }}
            >
              <span className="text-[13px]" style={{ color: COLORS.ink }}>
                {r.label}
              </span>
              {r.detail != null && (
                <span className="text-[12px]" style={{ color: COLORS.inkSubtle }}>
                  {r.detail}
                </span>
              )}
            </div>
          ))
        )}
      </div>
    </section>
  );
}

export default ToolAcquisition;
