export const HEIRLOOMS = [
  {
    id: 'harvestmoon',
    name: 'Harvest Moon',
    desc: '+1 to all chain harvest counts.',
    rarity: 'rare',
    icon: '🌙',
    effect: { type: 'chain_harvest_bonus', value: 1 },
  },
  {
    id: 'oldcoin',
    name: 'Old Coin',
    desc: 'Orders pay +10% coins.',
    rarity: 'common',
    icon: '🪙',
    effect: { type: 'order_coin_pct', value: 0.1 },
  },
  {
    id: 'seedring',
    name: 'Seed Ring',
    desc: 'Every season starts with +5 hay.',
    rarity: 'common',
    icon: '🌱',
    effect: { type: 'season_start_hay', value: 5 },
  },
  {
    id: 'forgemark',
    name: 'Forge Mark',
    desc: 'Mine biome gives +1 ingot/cobble per chain.',
    rarity: 'rare',
    icon: '⚒',
    effect: { type: 'mine_chain_bonus', value: 1 },
  },
  {
    id: 'stoneheart',
    name: 'Stone Heart',
    desc: 'Buildings cost 5% less.',
    rarity: 'common',
    icon: '💎',
    effect: { type: 'building_cost_pct', value: -0.05 },
  },
  {
    id: 'windsong',
    name: 'Wind Song',
    desc: 'Reshuffle Horn refunds 1 turn.',
    rarity: 'rare',
    icon: '🎐',
    effect: { type: 'horn_turn_refund', value: 1 },
  },
  {
    id: 'lumberknot',
    name: 'Lumber Knot',
    desc: 'Logs spawn 20% more often in farm pool.',
    rarity: 'common',
    icon: '🪵',
    effect: { type: 'log_spawn_pct', value: 0.2 },
  },
  {
    id: 'embershard',
    name: 'Ember Shard',
    desc: 'First chain of every season is doubled.',
    rarity: 'legendary',
    icon: '🔥',
    effect: { type: 'first_chain_double', value: true },
  },
  {
    id: 'chimes',
    name: 'Chimes',
    desc: 'NPC bubbles linger 50% longer.',
    rarity: 'common',
    icon: '🔔',
    effect: { type: 'bubble_duration_pct', value: 0.5 },
  },
  {
    id: 'tinder',
    name: 'Tinder',
    desc: 'Chains of 6+ give +2 XP.',
    rarity: 'common',
    icon: '✨',
    effect: { type: 'long_chain_xp', value: 2 },
  },
  {
    id: 'palecrown',
    name: 'Pale Crown',
    desc: '+1 building level cap discount (any L8+ unlocks at L7).',
    rarity: 'legendary',
    icon: '👑',
    effect: { type: 'building_level_cap_discount', value: 1 },
  },
  {
    id: 'cartographer',
    name: 'Cartographer',
    desc: 'Map reveals 2 extra routes.',
    rarity: 'rare',
    icon: '🗺',
    effect: { type: 'map_extra_routes', value: 2 },
  },
];

export const HEIRLOOM_MAP = Object.fromEntries(HEIRLOOMS.map(h => [h.id, h]));
