/**
 * Config Reference generator for docs/progression-plan-v2.html.
 *
 * Runs under vitest (`npm run gen:config-doc`) so it loads the canonical TS
 * config through the same module loader the test suite uses — plain esbuild /
 * vite-SSR can't, because of the constants↔balance↔tileCollection import cycle.
 *
 * It imports the LIVE config maps, renders HTML tables, and replaces everything
 * between the GEN markers in the doc. Counts are computed, so they can't drift.
 */
import { test, expect } from "vitest";
import { readFileSync, writeFileSync } from "node:fs";
import { execSync } from "node:child_process";
import { resolve } from "node:path";
import * as C from "../../src/constants";
import * as cart from "../../src/features/cartography/data";
import * as wk from "../../src/features/workers/data";
import * as tp from "../../src/config/toolPowers";
import * as bossMod from "../../src/features/bosses/data";
import * as npcMod from "../../src/features/npcs/data";
import * as achMod from "../../src/features/achievements/data";

const DOC = resolve(__dirname, "../../docs/progression-plan-v2.html");
const START = "<!-- GEN:config-reference START — generated by `npm run gen:config-doc`; do not hand-edit -->";
const END = "<!-- GEN:config-reference END -->";

const ITEMS: Record<string, any> = (C as any).ITEMS;
const BUILDINGS: any[] = (C as any).BUILDINGS;
const RECIPES: Record<string, any> = (C as any).RECIPES;
const THRESH: Record<string, number> = (C as any).UPGRADE_THRESHOLDS;
const SELL_RATE = 0.1;

const esc = (s: any) => String(s).replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
const byKind = (k: string) => Object.entries(ITEMS).filter(([, v]) => v.kind === k);
const firstArray = (m: any): any[] => {
  if (Array.isArray(m)) return m;
  for (const v of Object.values(m)) if (Array.isArray(v)) return v as any[];
  return [];
};
const len = (m: any): number => (Array.isArray(m) ? m.length : Object.keys(m ?? {}).length);

function costStr(cost: any): string {
  if (!cost) return "—";
  const parts: string[] = [];
  if (cost.coins) parts.push(`${cost.coins}c`);
  for (const [k, v] of Object.entries(cost)) if (k !== "coins") parts.push(`${v} ${k}`);
  return parts.join(" + ") || "free";
}
function inputsStr(inputs: any): string {
  if (!inputs) return "—";
  return Object.entries(inputs).map(([k, v]) => `${k}×${v}`).join(", ");
}

// ---- counts (the anti-drift centrepiece) -----------------------------------
const tiles = byKind("tile");
const tileBiome: Record<string, number> = {};
for (const [, v] of tiles) tileBiome[v.biome] = (tileBiome[v.biome] || 0) + 1;
const resources = byKind("resource");
const tools = byKind("tool");
const recipeBase = Object.keys(RECIPES).filter((k) => k.startsWith("rec_"));
const toolPowers = firstArray((tp as any).TOOL_POWERS ?? tp);
const mapNodes = firstArray((cart as any).MAP_NODES);
const regions = (cart as any).REGIONS ?? (cart as any).MAP_REGIONS;
const bosses = firstArray((bossMod as any).BOSSES);
const npcs = (npcMod as any).NPC_IDS ?? firstArray(npcMod);
const achievements = firstArray((achMod as any).ACHIEVEMENTS ?? achMod);
const workers = firstArray((wk as any).TYPE_WORKERS);

const sha = (() => { try { return execSync("git rev-parse --short HEAD").toString().trim(); } catch { return "local"; } })();
const today = new Date().toISOString().slice(0, 10);

const countsRows = [
  ["Tiles", `${tiles.length}`, `farm ${tileBiome.farm ?? 0} · mine ${tileBiome.mine ?? 0} · fish ${tileBiome.fish ?? 0}`],
  ["Resources", `${resources.length}`, `41 canonical + 3 display aliases`],
  ["Tools", `${tools.length}`, `each driven by a tool-power id`],
  ["Tool powers", `${toolPowers.length}`, `live TOOL_POWERS (deferred set removed in #807)`],
  ["Buildings", `${BUILDINGS.length}`, `housing/housing2/housing3 are 3 rows`],
  ["Recipes", `${recipeBase.length}`, `base rec_* keys (+${Object.keys(RECIPES).length - recipeBase.length} item-name aliases = ${Object.keys(RECIPES).length} total)`],
  ["Upgrade thresholds", `${Object.keys(THRESH).length}`, `per-tile chain length`],
  ["Map nodes", `${mapNodes.length}`, `across ${len(regions)} regions`],
  ["Bosses", `${bosses.length}`, `paused in Phase 1`],
  ["NPCs", `${len(npcs)}`, `bonds 0–10`],
  ["Achievements", `${achievements.length}`, ``],
  ["Worker types", `${workers.length}`, `placeholders; expand per chain step`],
  ["SAVE_SCHEMA_VERSION", `${(C as any).SAVE_SCHEMA_VERSION}`, `mismatched saves discarded`],
];

// ---- table builders --------------------------------------------------------
function table(head: string[], rows: string[][], cls = ""): string {
  return `<div class="scrollx"><table${cls ? ` class="${cls}"` : ""}>
<thead><tr>${head.map((h) => `<th>${h}</th>`).join("")}</tr></thead>
<tbody>
${rows.map((r) => `<tr>${r.map((c, i) => `<td${i > 0 && /^[\d.+ c×—-]*$/.test(c) ? ' class="num"' : ""}>${c}</td>`).join("")}</tr>`).join("\n")}
</tbody></table></div>`;
}

const countsTable = table(["Concept", "Live count", "Note"], countsRows);

const resourceRows = resources
  .map(([k, v]) => [`<code>${esc(k)}</code>`, esc(v.label ?? ""), `${v.value ?? 0}`, `${Math.round((v.value ?? 0) * SELL_RATE)}`])
  .sort((a, b) => Number(a[2]) - Number(b[2]));
const resourceTable = table(["key", "label", "value", "sell ×0.10"], resourceRows);

const buildingRows = BUILDINGS.map((b) => [
  `<code>${esc(b.id)}</code>`, `${b.lv ?? 1}`, esc(costStr(b.cost)),
  esc((b.abilities ?? []).map((a: any) => a.id).join(", ") || "—"),
]);
const buildingTable = table(["id", "lv", "cost", "abilities"], buildingRows);

const recipeRows = recipeBase.map((k) => {
  const r = RECIPES[k];
  return [`<code>${esc(r.item ?? k)}</code>`, esc(r.station ?? "—"), esc(inputsStr(r.inputs)), `${r.coins ?? 0}`];
});
const recipeTable = table(["item", "station", "inputs", "coins"], recipeRows);

const toolRows = tools.map(([k, v]) => [`<code>${esc(k)}</code>`, esc(v.label ?? ""), `<code>${esc(v.power?.id ?? "—")}</code>`]);
const toolTable = table(["key", "label", "power"], toolRows);

const workerRows = workers.map((w: any) => {
  const ab = (w.abilities ?? [])[0];
  const target = ab?.params?.category ?? ab?.params?.recipe ?? "—";
  return [`<code>${esc(w.id)}</code>`, esc(w.name ?? ""), `<code>${esc(ab?.id ?? "—")}</code>`, esc(`${target} −${ab?.params?.amount ?? 0}`)];
});
const workerTable = table(["id", "name", "ability", "effect"], workerRows);

const poolCount = (pool: any[]) => {
  const m: Record<string, number> = {};
  for (const t of pool) m[t] = (m[t] || 0) + 1;
  return Object.entries(m).map(([k, n]) => `${k.replace(/^tile_/, "")}×${n}`).join(", ");
};
const poolTable = table(["pool", "slots (tile×count)"], [
  ["FARM_TILE_POOL", esc(poolCount((C as any).FARM_TILE_POOL))],
  ["MINE_TILE_POOL", esc(poolCount((C as any).MINE_TILE_POOL))],
  ["FISH_TILE_POOL", esc(poolCount((C as any).FISH_TILE_POOL))],
]);

const threshRows = Object.entries(THRESH).map(([k, v]) => [`<code>${esc(k.replace(/^tile_/, ""))}</code>`, `${v}`]);
const threshTable = table(["tile", "T"], threshRows);

// ---- assemble fragment -----------------------------------------------------
const fragment = `${START}
<p class="legend">Generated from the canonical TypeScript by <code>npm run gen:config-doc</code> · source commit <code>${sha}</code> · ${today}. Re-run after editing configs; never hand-edit between these markers.</p>

<h3>Live counts</h3>
${countsTable}

<h3>Resources <span class="muted">(catalog value · Market sell = round(value × 0.10))</span></h3>
${resourceTable}

<h3>Buildings</h3>
${buildingTable}

<h3>Tile spawn pools &amp; thresholds</h3>
${poolTable}

<h3>Workers</h3>
${workerTable}

<details><summary>Recipes (${recipeBase.length} base) · Tools (${tools.length}) · Upgrade thresholds (${Object.keys(THRESH).length})</summary>
<h4>Recipes (base <code>rec_*</code>)</h4>
${recipeTable}
<h4>Tools</h4>
${toolTable}
<h4>Upgrade thresholds</h4>
${threshTable}
</details>
${END}`;

test("generate config reference into the doc", () => {
  const html = readFileSync(DOC, "utf8");
  const s = html.indexOf(START.split(" — ")[0]); // tolerate marker text drift on START prefix
  const startIdx = html.indexOf(START);
  const endIdx = html.indexOf(END);
  if (startIdx === -1 || endIdx === -1) {
    throw new Error(`Config-reference markers not found in ${DOC}. Add:\n${START}\n${END}\nbetween them.`);
  }
  const next = html.slice(0, startIdx) + fragment + html.slice(endIdx + END.length);
  writeFileSync(DOC, next);
  // eslint-disable-next-line no-console
  console.log(`[gen:config-doc] tiles ${tiles.length} · resources ${resources.length} · tools ${tools.length} · powers ${toolPowers.length} · buildings ${BUILDINGS.length} · recipes ${recipeBase.length} (base) · @ ${sha}`);
  expect(startIdx).toBeLessThan(endIdx);
  void s;
});
