export const APPRENTICES = [
  {
    id: "hilda",
    name: "Hilda",
    role: "Farmhand",
    icon: "🧑‍🌾",
    color: "#4f8c3a",
    wage: 30,
    produces: { hay: 8, log: 4 },
    hireCost: 200,
    requirement: { building: "granary" },
  },
  {
    id: "dren",
    name: "Dren",
    role: "Miner",
    icon: "⛏",
    color: "#7a8490",
    wage: 50,
    produces: { stone: 6, ore: 3 },
    hireCost: 350,
    requirement: { level: 2 },
  },
  {
    id: "pip",
    name: "Pip",
    role: "Forager",
    icon: "🌿",
    color: "#7dc45a",
    wage: 25,
    produces: { berry: 5, egg: 2 },
    hireCost: 150,
    requirement: null,
  },
  {
    id: "osric",
    name: "Osric",
    role: "Smith Apprentice",
    icon: "⚒",
    color: "#3a3a3a",
    wage: 80,
    produces: { ingot: 1, plank: 4 },
    hireCost: 500,
    requirement: { building: "forge", orLevel: 4 },
  },
  {
    id: "wila",
    name: "Wila",
    role: "Cellarer",
    icon: "🍯",
    color: "#c8923a",
    wage: 40,
    produces: { jam: 2, flour: 3 },
    hireCost: 300,
    requirement: { building: "bakery" },
  },
  {
    id: "tuck",
    name: "Tuck",
    role: "Lookout",
    icon: "👀",
    color: "#3a6a9a",
    wage: 20,
    produces: { coins: 25 },
    hireCost: 100,
    requirement: null,
  },
];

export const APPRENTICE_MAP = Object.fromEntries(APPRENTICES.map((a) => [a.id, a]));
